# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Заявка на парсинг', 'verbose_name_plural': 'Заявки на парсинг'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='day_shedule',
            field=models.ImageField(default='', upload_to='/images/orders/shedules2017-06-22 16:08:24.008483'),
            preserve_default=False,
        ),
    ]
