# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_main_app', '0003_auto_20170622_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='hour_shedule',
            field=models.ImageField(null=True, upload_to='images/orders/shedules20176221712'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='day_shedule',
            field=models.ImageField(null=True, upload_to='images/orders/shedules20176221712'),
        ),
    ]
