# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_main_app', '0007_auto_20170623_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='hour_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules20176231345'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='week_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules20176231345'),
        ),
    ]
