# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_main_app', '0013_auto_20170624_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='hour_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules2017731735'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='week_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules2017731735'),
        ),
    ]
