# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_main_app', '0015_auto_20170703_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='hour_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules2017111200'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='week_shedule',
            field=models.ImageField(blank=True, null=True, upload_to='images/orders/shedules2017111200'),
        ),
    ]
